"""
GridPulse — API içinde çalışan otonom agent döngüsü
Telemetri izler, karar üretir, kritik durumlarda e-posta raporu gönderir.
"""
import random
import threading
import time
from datetime import datetime

import requests

from backend.report_service import (
    compose_ops_report,
    get_agent_config,
    send_report_email,
)

LOOP_INTERVAL_SEC = 3
PROACTIVE_CHART_EVERY_N = 2  # her ~6 sn yeni otonom grafik
MAX_CANVAS_CHARTS = 36
_last_periodic_report = 0.0
_last_critical_report: dict = {}
_last_outage_report = 0.0
_stream_healthy = True
_loop_thread = None
_loop_running = False
_loop_tick = 0
_proactive_idx = 0


RULE_MAP = {
    "CRITICAL_OVERLOAD": {"rule": "Rule 101", "severity": "CRITICAL", "chart_type": "load", "action": "SPAWN_CHART"},
    "OVERHEATING": {"rule": "Rule 103", "severity": "HIGH", "chart_type": "temperature", "action": "SPAWN_CHART"},
    "VOLTAGE_DROP": {"rule": "Rule 102", "severity": "HIGH", "chart_type": "voltage", "action": "SPAWN_CHART"},
}

PROACTIVE_CHART_SCENARIOS = [
    {"chart_type": "load", "device_id": "TRAFO_301", "rule": "Rule 101", "severity": "LOW",
     "title": "TRAFO_301 — Aktif Yük", "msg_tr": "Otonom tarama: ana trafo yük eğrisi güncellendi.", "msg_en": "Autonomous scan: main transformer load curve refreshed."},
    {"chart_type": "voltage", "device_id": "TRAFO_302", "rule": "Rule 102", "severity": "LOW",
     "title": "TRAFO_302 — Faz Gerilimi", "msg_tr": "Agent voltaj profilini yeniden çizdi — faz dengesi izleniyor.", "msg_en": "Agent redrawn voltage profile — phase balance monitored."},
    {"chart_type": "temperature", "device_id": "CHARGER_201", "rule": "Rule 103", "severity": "MEDIUM",
     "title": "CHARGER_201 — Termal", "msg_tr": "EV şarj ünitesi termal eğrisi otonom üretildi.", "msg_en": "EV charger thermal curve autonomously generated."},
    {"chart_type": "power_factor", "device_id": "METER_101", "rule": "Rule 104", "severity": "LOW",
     "title": "METER_101 — Güç Faktörü", "msg_tr": "Reaktif yük ve cos φ trendi agent tarafından eklendi.", "msg_en": "Reactive load and cos φ trend added by agent."},
    {"chart_type": "frequency", "device_id": "GRID_FREQ", "rule": "Rule 105", "severity": "LOW",
     "title": "Şebeke Frekansı", "msg_tr": "50 Hz nominal band analizi — otonom frekans grafiği.", "msg_en": "50 Hz nominal band analysis — autonomous frequency chart."},
    {"chart_type": "thd", "device_id": "HARMONIC_01", "rule": "Rule 106", "severity": "MEDIUM",
     "title": "THD Harmonik", "msg_tr": "Harmonik bozulma profili agent tarafından tarandı.", "msg_en": "Harmonic distortion profile scanned by agent."},
    {"chart_type": "region_bar", "device_id": "REGION_WEST", "rule": "Rule 107", "severity": "LOW",
     "title": "Bölgesel Tüketim", "msg_tr": "Westminster/Camden bölgesel yük dağılımı güncellendi.", "msg_en": "Westminster/Camden regional load distribution updated."},
    {"chart_type": "radar", "device_id": "GRID_RADAR", "rule": "Rule 108", "severity": "LOW",
     "title": "Stabilite Radarı", "msg_tr": "5 boyutlu şebeke sağlık radarı otonom oluşturuldu.", "msg_en": "5-dimension grid health radar autonomously created."},
    {"chart_type": "scatter", "device_id": "ANOMALY_MAP", "rule": "Rule 109", "severity": "MEDIUM",
     "title": "Anomali Dağılımı", "msg_tr": "Son olayların saçılım haritası agent tarafından üretildi.", "msg_en": "Event scatter map generated by agent."},
    {"chart_type": "leakage", "device_id": "LOSS_SUB_A", "rule": "Rule 110", "severity": "LOW",
     "title": "Kaçak Kayıp", "msg_tr": "Alt istasyon teknik kayıp oranı grafiği eklendi.", "msg_en": "Substation technical loss rate chart added."},
    {"chart_type": "compliance_pie", "device_id": "COMPLIANCE", "rule": "Rule 111", "severity": "LOW",
     "title": "Uyumluluk Dağılımı", "msg_tr": "Kural tetikleme kırılımı otonom güncellendi.", "msg_en": "Rule trigger breakdown autonomously updated."},
    {"chart_type": "timeline", "device_id": "GRID_24H", "rule": "Rule 112", "severity": "LOW",
     "title": "24s Uyumluluk", "msg_tr": "Günlük uyumluluk zaman çizelgesi agent tarafından çizildi.", "msg_en": "Daily compliance timeline drawn by agent."},
]


def _api_base():
    return "http://127.0.0.1:8000"


def _log(msg: str):
    try:
        requests.post(f"{_api_base()}/api/agent/log", json={"log": msg}, timeout=2)
    except Exception:
        pass


def _get_status() -> dict:
    try:
        r = requests.get(f"{_api_base()}/api/agent/status", timeout=2)
        return r.json()
    except Exception:
        return {"active": False}


def _rule_based_decision(telemetry: dict) -> dict:
    reason = telemetry.get("reason", "NORMAL")
    device = telemetry.get("device_id", "UNKNOWN")
    if reason == "NORMAL":
        return {"status": "NORMAL", "action": "NONE"}

    meta = RULE_MAP.get(reason, {"rule": "Rule 110", "severity": "MEDIUM", "chart_type": "timeline", "action": "SPAWN_CHART"})
    messages = {
        "CRITICAL_OVERLOAD": f"{device} aşırı yük altında — yük dengeleme ve izolasyon değerlendirilmeli.",
        "OVERHEATING": f"{device} termal limit aşıldı — soğutma ve koruma devreye alınmalı.",
        "VOLTAGE_DROP": f"{device} voltaj düşüşü — faz dengesi kontrol edilmeli.",
    }
    return {
        "status": "ANOMALY",
        "rule": meta["rule"],
        "severity": meta["severity"],
        "device": device,
        "action": meta["action"],
        "chart_type": meta["chart_type"],
        "widget_title": f"{device} — {meta['rule']}",
        "message": messages.get(reason, f"{device} anomali tespit edildi."),
    }


def _check_system_health() -> dict:
    try:
        r = requests.get(f"{_api_base()}/api/status", timeout=2)
        return r.json()
    except Exception:
        return {"clickhouse": "OFFLINE", "redpanda": "OFFLINE", "sqlite_rag": "OFFLINE", "ollama": "OFFLINE"}


def _handle_data_outage(services: dict):
    global _last_outage_report, _stream_healthy
    offline = [k for k, v in services.items() if v == "OFFLINE"]
    if not offline:
        if not _stream_healthy:
            _log("[AGENT] ✅ Veri akışı yeniden kuruldu — sistem normale döndü")
        _stream_healthy = True
        return

    now = time.time()
    if now - _last_outage_report < 180:
        return

    _stream_healthy = False
    _last_outage_report = now
    _log(f"[AGENT] 🔴 VERİ KESİNTİSİ — offline servisler: {', '.join(offline)}")
    _log("[AGENT] 📧 Veri kesintisi raporu hazırlanıyor...")
    _dispatch_report("data_outage", trigger={"offline_services": offline, "reason": "DATA_OUTAGE"})


def _dispatch_report(report_type: str, trigger: dict = None, lang: str = "TR"):
    global _last_periodic_report
    config = get_agent_config()
    if not config.get("auto_report_enabled"):
        return None

    try:
        actions_r = requests.get(f"{_api_base()}/api/agent/actions", timeout=3)
        logs_r = requests.get(f"{_api_base()}/api/agent/logs", timeout=3)
        actions_data = actions_r.json()
        logs_data = logs_r.json()

        report = compose_ops_report(
            report_type=report_type,
            agent_status=actions_data.get("status", "SAFE"),
            agent_actions=actions_data.get("actions", []),
            agent_logs=logs_data.get("logs", []),
            trigger=trigger,
            lang=lang,
        )
        result = send_report_email(
            config["ops_email"],
            report["subject"],
            report["html"],
            report["text"],
        )
        status_label = {"sent": "gönderildi", "queued": "outbox'a kaydedildi", "failed": "başarısız"}.get(result["status"], result["status"])
        _log(f"[REPORT] 📧 Rapor {status_label} → {config['ops_email']} | {report['subject']}")
        return result
    except Exception as e:
        _log(f"[REPORT] ❌ Rapor hatası: {e}")
        return None


def _post_chart_action(payload: dict):
    try:
        requests.post(f"{_api_base()}/api/agent/action", json=payload, timeout=3)
        return True
    except Exception:
        return False


def _refresh_proactive_chart(telemetry: dict, lang: str = "TR"):
    """Mevcut tuval slotunu telemetriyle yenile (yeni kart eklemez)"""
    global _proactive_idx
    scenario = PROACTIVE_CHART_SCENARIOS[_proactive_idx % len(PROACTIVE_CHART_SCENARIOS)]
    _proactive_idx += 1

    device = telemetry.get("device_id", scenario["device_id"])
    reason = telemetry.get("reason", "NORMAL")
    severity = scenario["severity"]
    if reason == "CRITICAL_OVERLOAD":
        severity = "HIGH"
    elif reason in ("OVERHEATING", "VOLTAGE_DROP"):
        severity = "MEDIUM"

    ts = datetime.now().strftime("%H:%M:%S")
    msg = scenario["msg_tr"] if lang.upper() == "TR" else scenario["msg_en"]
    if reason != "NORMAL":
        msg += f" Tetikleyici: {reason} ({device})."
    msg += f" [{ts} yenilendi]"

    slot_id = f"{scenario['device_id']}:{scenario['chart_type']}"
    payload = {
        "device_id": scenario["device_id"],
        "action": "SPAWN_CHART",
        "chart_type": scenario["chart_type"],
        "widget_title": scenario["title"],
        "severity": severity,
        "rule": scenario["rule"],
        "message": msg,
        "timestamp": ts,
        "slot_id": slot_id,
        "refresh": True,
        "autonomous": True,
        "lang": lang,
    }
    if _post_chart_action(payload):
        _log(f"[{ts}] [AGENT] 🔄 Grafik yenilendi → {scenario['title']}")
        _log(f"[{ts}] [VISION] 👁 {scenario['chart_type']} yorumu güncellendi")


def _process_telemetry(telemetry: dict):
    global _last_critical_report
    device = telemetry.get("device_id", "UNKNOWN")
    reason = telemetry.get("reason", "NORMAL")
    ts = datetime.now().strftime("%H:%M:%S")

    if reason == "NORMAL":
        return

    _log(f"[{ts}] [{device}] ⚠ Anomali: {reason} — agent analiz ediyor...")
    _log(f"[{ts}] [AGENT] 🔍 Soru: {device} için {reason} kural eşleşmesi doğrulanıyor...")

    decision = _rule_based_decision(telemetry)
    if decision.get("action") == "NONE":
        return

    severity = decision.get("severity", "LOW")
    _log(f"[{ts}] [{device}] 🤖 KARAR → {decision['action']} | {decision['rule']} | {severity}")
    _log(f"[{ts}] [{device}] 💬 {decision.get('message', '')}")

    chart_type = decision.get("chart_type", "timeline")
    slot_id = f"{device}:{chart_type}"
    payload = {
        "device_id": device,
        "action": decision["action"],
        "chart_type": chart_type,
        "widget_title": decision.get("widget_title"),
        "severity": severity,
        "rule": decision.get("rule"),
        "message": f"{decision.get('message', '')} [{ts} yenilendi]",
        "timestamp": ts,
        "slot_id": slot_id,
        "refresh": True,
        "autonomous": True,
    }
    if _post_chart_action(payload):
        _log(f"[{ts}] [{device}] ✅ Grafik komutu gönderildi")
        chart_type = decision.get("chart_type", "")
        _log(f"[{ts}] [VISION] 👁 {chart_type} grafiği okunuyor ve yorumlanıyor...")

    if severity in ("CRITICAL", "HIGH"):
        dedup_key = f"{device}:{decision.get('rule')}"
        now = time.time()
        if now - _last_critical_report.get(dedup_key, 0) > 120:
            _last_critical_report[dedup_key] = now
            _log(f"[{ts}] [AGENT] 📧 Kritik rapor hazırlanıyor → operatör e-postası...")
            _dispatch_report("critical_alert", trigger={**payload, "reason": reason})


def _fetch_telemetry() -> dict:
    devices = ["TRAFO_301", "TRAFO_302", "CHARGER_201", "CHARGER_203", "METER_101", "METER_103"]
    cities = ["Wembley", "Wimbledon", "Greenwich", "Hackney", "Westminster", "Camden"]
    device = random.choice(devices)
    city = random.choice(cities)
    reason = "NORMAL"
    if random.random() < 0.35:
        reason = random.choice(["CRITICAL_OVERLOAD", "OVERHEATING", "VOLTAGE_DROP"])
    consumption = random.randint(120, 480)
    voltage = random.randint(218, 242)
    temp = random.randint(20, 80)
    if reason == "CRITICAL_OVERLOAD":
        consumption = random.randint(510, 600)
    elif reason == "OVERHEATING":
        temp = random.randint(91, 105)
    elif reason == "VOLTAGE_DROP":
        voltage = random.randint(180, 215)
    return {
        "device_id": device,
        "location": city,
        "consumption": consumption,
        "voltage": voltage,
        "temp": temp,
        "reason": reason,
        "timestamp": datetime.utcnow().isoformat() + "Z",
    }


def _loop():
    global _last_periodic_report, _loop_running, _loop_tick
    _log("[SYS] Otonom agent döngüsü aktif — telemetri + otonom grafik tuvali + raporlama")
    while _loop_running:
        try:
            status = _get_status()
            if not status.get("active"):
                time.sleep(2)
                continue

            health = _check_system_health()
            _handle_data_outage(health)

            telemetry = _fetch_telemetry()
            _loop_tick += 1

            # Her döngüde otonom grafik üret (tuval canlı kalsın)
            if _loop_tick % PROACTIVE_CHART_EVERY_N == 0:
                _refresh_proactive_chart(telemetry, "TR")

            _process_telemetry(telemetry)

            config = get_agent_config()
            interval = config.get("report_interval_minutes", 5) * 60
            now = time.time()
            if now - _last_periodic_report >= interval:
                _last_periodic_report = now
                _log("[AGENT] 📊 Periyodik operasyon özeti hazırlanıyor...")
                _dispatch_report("periodic_digest")

        except Exception as e:
            _log(f"[ERR] Otonom döngü: {e}")

        time.sleep(LOOP_INTERVAL_SEC)


def start_autonomous_loop():
    global _loop_thread, _loop_running
    if _loop_running:
        return
    _loop_running = True
    _loop_thread = threading.Thread(target=_loop, daemon=True, name="gridpulse-autonomous")
    _loop_thread.start()


def stop_autonomous_loop():
    global _loop_running
    _loop_running = False


def send_startup_report():
    global _last_periodic_report
    _last_periodic_report = time.time()
    config = get_agent_config()
    _log(f"[SYS] 📧 Başlangıç raporu hazırlanıyor → {config['ops_email']}")
    return _dispatch_report("autopilot_start")
